package com.example.taskapplication.room;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity
public class Users {


    @PrimaryKey(autoGenerate = true)
    private int id;
    //**** THE ID WILL BE GENERATED BY AUTOMATICALLY BY 1

    private String name;
    private String email;
    private String address;
    private String gender;
    private String description;


    //** NOW WE MAKING A PARAMETRIZED CONSTRUCTOR.


    public Users(int id, String name, String email, String address, String gender, String description) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.address = address;
        this.gender = gender;
        this.description = description;
    }


    //**  HERE WE MAKE A GETTER AND SETTER.


    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
